version: "3.8"
services:
  dc-bot:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    environment:
      TOKEN: ${TOKEN}
      API_ENDPOINT: ${API_ENDPOINT}